server:
  port: 9998

# application.yml
api:
  url: http://localhost/v1
  key: app-HdDir9lLF2cGLkLJ6NZWPpgm


# ?????
spring:
  resttemplate:
    read-timeout: 5000
    connection-timeout: 3000
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: '190687'
    url: jdbc:mysql://localhost:3306/code2025?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=GMT%2b8&allowPublicKeyRetrieval=true
# ??mybatis???xml??
mybatis:
  ## ??xml
  mapper-locations: classpath:mapper/*.xml
  configuration:
    # ????
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
